export const GET_MOVIES='GET_MOVIES';
export const REMOVE_MOVIE='REMOVE_MOVIE';
export const DETAILS_MOVIE='DETAILS_MOVIE';
export const ERROR_MOVIE='ERROR_MOVIE';
export const SET_LOADING = 'SET_LOADING';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const ADD_MOVIE = 'ADD_MOVIE';
export const GET_MOVIE = 'GET_MOVIE';
